version: '3.8'

services:
  # Main App DB
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: sayan
      POSTGRES_PASSWORD: sayan
      POSTGRES_DB: paper_exam_grader
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # MinIO
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    restart: always
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: sayan
      MINIO_ROOT_PASSWORD: sayan123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  #auth
  auth_service:
    ports:
      - "8082:8082"
    build:
      context: /Users/sayanseksenbaev/Programming/go-project/services/authService
      dockerfile: Dockerfile
    container_name: authservice
    env_file:
      - .env
    depends_on:
      - auth_db
    environment:
      DATABASE_URL: ${AUTH_DATABASE_URL}
      PORT: 8082
      JWT_SECRET: ${JWT_SECRET}

  auth_db:
    image: postgres:16
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
    volumes:
      - auth_db:/var/lib/postgresql/data
  paper_exam_grader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paper_exam_grader
    ports:
      - "8081:8081"
    depends_on:
      - db
      - minio
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${ACCESS_KEY}
      MINIO_SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
    env_file:
      - .env
volumes:
  database:
    driver: local
  redis:
    driver: local
  pgdata:
  auth_db:
  minio_data: