version: '3.8'

services:
  # Main App DB
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: sayan
      POSTGRES_PASSWORD: sayan
      POSTGRES_DB: paper_exam_grader
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # MinIO
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    restart: always
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: sayan
      MINIO_ROOT_PASSWORD: sayan123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"


volumes:
  database:
    driver: local
  redis:
    driver: local
  pgdata:
  minio_data: